- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create namespaces
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ item }}"
      loop:
        - demo-dev
        - demo-prod
        - demo-staging
        - monitoring

