- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create namespace 'dev'
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: dev
