- hosts: localhost
  gather_facts: false
  tasks:
    - name: Deploy nginx pod in 'dev' namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: demo-nginx
            namespace: dev
          spec:
            containers:
              - name: nginx
                image: nginx:latest
                ports:
                  - containerPort: 80
