- name: Setup Velero Backup system
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Add VMware Tanzu Helm repo
      kubernetes.core.helm_repository:
        name: vmware-tanzu
        repo_url: https://vmware-tanzu.github.io/helm-charts

    - name: Deploy Velero using Helm
      kubernetes.core.helm:
        name: velero
        chart_ref: vmware-tanzu/velero
        release_namespace: velero
        create_namespace: true
        values:
          configuration:
            backupStorageLocation:
              - name: default
                provider: aws
                bucket: velero-backups
                config:
                  region: us-east-1
            volumeSnapshotLocation:
              - name: default
                provider: aws
                config:
                  region: us-east-1
          credentials:
            useSecret: false
          deployNodeAgent: true
